### ISSUE TITLE
Add groups

### ISSUE THREAD

**Issue by michaeldavie** [m-radzikowski/diagrams-aws-icons#2]
Add the groups defined in AWS's PowerPoint toolkit.

![image](https://user-images.githubusercontent.com/16008714/163715707-d36c7956-90ce-4170-8ed7-59d061556533.png)

![image](https://user-images.githubusercontent.com/16008714/163715716-562d25d8-bbef-4f33-9f79-76730c730839.png)

![image](https://user-images.githubusercontent.com/16008714/163715723-f1844e84-791e-4e16-97d5-0f5c637c6cf8.png)

**Comment by m-radzikowski** [comment]
Hey, it's a good idea. As I noted in the other issue (#1), the library is generated with a script from the icons pack. Those groups could be generated either manually in diagrams.net, exported, and added to the repo, or automated with a separate script. I think the manual option may be just simpler and easier, especially since any bigger change in groups would require changing the script.

If you are willing to create such a library feel free to send a PR or even just attach the library file here in the issue so I can integrate it into the repo.

**Comment by michaeldavie** [comment]
Thanks, I’ll take a look at the existing group definitions and your script and see if I can figure out a way to automate at least some of them.

**Comment by m-radzikowski** [comment]
Hey, I've added groups in the latest version (2024-02-06).
